name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification on Success
        if: always()
        uses: lazy-actions/slatify@master
        with:
          type: ${{ job.status }}
          job_name: '*Test*'
          channel: '#infra_slack_test'
          mention: 'here'
          mention_if: 'failure'
          url: ${{ secrets.SLACK_WEBHOOK }}
