name: CI

on:
  push:
    branches: [ master ]

env:
  # 環境変数にWebhookのURLを設定
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification on Success
        if: always()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: general
          SLACK_USERNAME: rtCamp
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: 'Workflow #${{ github.run_number }} succeeded'
          SLACK_COLOR: ${{ job.status }}
